super_small_font  = ('Arial' , 8)
super_small_font_bold  = ('Arial' , 8 , 'bold')
small_font = ('Arial' , 12)
small_font_bold  = ('Arial' , 12 , 'bold')
medium_font  = ('Arial' , 15 )
medium_font_bold = ('Arial' , 15 , 'bold')
large_font  = ('Arial' , 20)
large_font_bold  = ('Arial' , 20 , 'bold')